include_recipe 'winrc::choco_package'
include_recipe 'winrc::path'
include_recipe 'winrc::msys2'
include_recipe 'winrc::gvim'
include_recipe 'winrc::dotfiles'
include_recipe 'winrc::stickies'
include_recipe 'winrc::repository_init'
